# Generated by Django 4.1.3 on 2022-12-22 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_alter_chat_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='avatar',
            field=models.ImageField(blank=True, default='default/account.png', null=True, upload_to='chat_avatars/'),
        ),
    ]
