# Generated by Django 4.1.3 on 2022-12-14 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msges', '0003_messageimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
