# Generated by Django 4.1.3 on 2022-12-15 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msges', '0004_alter_message_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='voice',
            field=models.FileField(blank=True, null=True, upload_to='message_voices/'),
        ),
    ]
